Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-7.0"

  config.vm.network "forwarded_port", host: 5080, guest: 80
  config.vm.network "forwarded_port", host: 8787, guest: 8787
  config.vm.network "forwarded_port", host: 3000, guest: 3000
  config.vm.network "forwarded_port", host: 9000, guest: 9000
  config.vm.network "forwarded_port", host: 9006, guest: 9006

  config.vm.provision :shell, path: "bootstrap.sh"
end
