# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "box-cutter/ubuntu1404-desktop"
    config.vm.network "forwarded_port", host: 5080, guest: 80
    config.vm.network "forwarded_port", host: 8787, guest: 8787
    config.vm.network "forwarded_port", host: 3000, guest: 3000
    config.vm.network "forwarded_port", host: 9000, guest: 9000
    config.vm.network "forwarded_port", host: 9006, guest: 9006
    config.vm.network "forwarded_port", host: 35729, guest: 35729
    config.ssh.forward_agent = true
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "1024"
    end
    config.vm.provision :shell, path: "bootstrap.sh"
end
