# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "box-cutter/ubuntu1404-desktop"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "1536"
    end
    config.vm.synced_folder "../install-scripts/", "/home/vagrant/install-scripts"
end
