- name: Install Haskell
  apt: name=haskell-platform update_cache=yes
- name: Clone CS Coursework Repo
  git: repo=git@bitbucket.org:rquez/cs-coursework.git dest={{ home }}/Workspace/cs-coursework accept_hostkey=yes force=yes key_file={{ home }}/.ssh/privateKey
- name: Get ownership of the CS Coursework Repo
  file: path={{ home }}/Workspace/cs-coursework owner={{ user }} recurse=yes
