$script = <<SCRIPT
if [ ! -f /usr/bin/ansible-playbook ]
	then
	apt-get install software-properties-common
	apt-add-repository ppa:ansible/ansible
	apt-get update
	apt-get install -y ansible
fi
ansible-galaxy install -r /vagrant/requirements.yml
ansible-playbook --inventory="localhost" -c local -s /vagrant/playbook.yml
SCRIPT
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 3000, host: 3000 

  config.vm.synced_folder "./", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
	vb.memory = 2048
	vb.cpus = 2
  end

  config.vm.provision "shell", inline: $script
end
