# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
if [ ! -f /usr/bin/ansible-playbook ]
	then
	apt-get install software-properties-common
	apt-add-repository ppa:ansible/ansible
	apt-get update
	apt-get install -y ansible
fi
ansible-galaxy install -r /vagrant/requirements.yml
ansible-playbook --inventory="localhost" -c local -s /vagrant/playbook.yml
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "geerlingguy/ubuntu1404"

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder ENV['ANSIBLE_ROLES'], "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    	vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provision "shell", inline: $script
end
